
CKEDITOR.replaceClass='ckeditor';(function(){CKEDITOR.replace=function(element,config){return createInstance(element,config,null,CKEDITOR.ELEMENT_MODE_REPLACE);};CKEDITOR.appendTo=function(element,config,data)
{return createInstance(element,config,data,CKEDITOR.ELEMENT_MODE_APPENDTO);};CKEDITOR.replaceAll=function(){var textareas=document.getElementsByTagName('textarea');for(var i=0;i<textareas.length;i++){var config=null,textarea=textareas[i];if(!textarea.name&&!textarea.id)
continue;if(typeof arguments[0]=='string'){var classRegex=new RegExp('(?:^|\\s)'+arguments[0]+'(?:$|\\s)');if(!classRegex.test(textarea.className))
continue;}else if(typeof arguments[0]=='function'){config={};if(arguments[0](textarea,config)===false)
continue;}
this.replace(textarea,config);}};CKEDITOR.editor.prototype.addMode=function(mode,exec){(this._.modes||(this._.modes={}))[mode]=exec;};CKEDITOR.editor.prototype.setMode=function(newMode,callback){var editor=this;var modes=this._.modes;if(newMode==editor.mode||!modes||!modes[newMode])
return;editor.fire('beforeSetMode',newMode);if(editor.mode){var isDirty=editor.checkDirty();editor._.previousMode=editor.mode;editor.fire('beforeModeUnload');editor.editable(0);editor.ui.space('contents').setHtml('');editor.mode='';}
this._.modes[newMode](function(){editor.mode=newMode;if(isDirty!==undefined)
!isDirty&&editor.resetDirty();setTimeout(function(){editor.fire('mode');callback&&callback.call(editor);},0);});};CKEDITOR.editor.prototype.resize=function(width,height,isContentHeight,resizeInner){var container=this.container,contents=this.ui.space('contents'),contentsFrame=CKEDITOR.env.webkit&&this.document&&this.document.getWindow().$.frameElement,outer=resizeInner?container.getChild(1):container;outer.setSize('width',width,true);contentsFrame&&(contentsFrame.style.width='1%');var delta=isContentHeight?0:(outer.$.offsetHeight||0)-(contents.$.clientHeight||0);contents.setStyle('height',Math.max(height-delta,0)+'px');contentsFrame&&(contentsFrame.style.width='100%');this.fire('resize');};CKEDITOR.editor.prototype.getResizable=function(forContents){return forContents?this.ui.space('contents'):this.container;};function createInstance(element,config,data,mode){if(!CKEDITOR.env.isCompatible)
return null;element=CKEDITOR.dom.element.get(element);if(element.getEditor())
throw'The editor instance "'+element.getEditor().name+'" is already attached to the provided element.';var editor=new CKEDITOR.editor(config,element,mode);if(mode==CKEDITOR.ELEMENT_MODE_REPLACE){element.setStyle('visibility','hidden');editor._.required=element.hasAttribute('required');element.removeAttribute('required');}
data&&editor.setData(data,null,true);editor.on('loaded',function(){loadTheme(editor);if(mode==CKEDITOR.ELEMENT_MODE_REPLACE&&editor.config.autoUpdateElement&&element.$.form)
editor._attachToForm();editor.setMode(editor.config.startupMode,function(){editor.resetDirty();editor.status='ready';editor.fireOnce('instanceReady');CKEDITOR.fire('instanceReady',null,editor);});});editor.on('destroy',destroy);return editor;}
function destroy(){var editor=this,container=editor.container,element=editor.element;if(container){container.clearCustomData();container.remove();}
if(element){element.clearCustomData();if(editor.elementMode==CKEDITOR.ELEMENT_MODE_REPLACE){element.show();if(editor._.required)
element.setAttribute('required','required');}
delete editor.element;}}
var themedTpl;function loadTheme(editor){var name=editor.name,element=editor.element,elementMode=editor.elementMode;var topHtml=editor.fire('uiSpace',{space:'top',html:''}).html;var bottomHtml=editor.fire('uiSpace',{space:'bottom',html:''}).html;if(!themedTpl){themedTpl=CKEDITOR.addTemplate('maincontainer','<{outerEl}'+' id="cke_{name}"'+' class="{id} cke cke_reset cke_chrome cke_editor_{name} cke_{langDir} '+CKEDITOR.env.cssClass+'" '+' dir="{langDir}"'+' lang="{langCode}"'+' role="application"'+' aria-labelledby="cke_{name}_arialbl">'+'<span id="cke_{name}_arialbl" class="cke_voice_label">{voiceLabel}</span>'+'<{outerEl} class="cke_inner cke_reset" role="presentation">'+'{topHtml}'+'<{outerEl} id="{contentId}" class="cke_contents cke_reset" role="presentation"></{outerEl}>'+'{bottomHtml}'+'</{outerEl}>'+'</{outerEl}>');}
var container=CKEDITOR.dom.element.createFromHtml(themedTpl.output({id:editor.id,name:name,langDir:editor.lang.dir,langCode:editor.langCode,voiceLabel:[editor.lang.editor,editor.name].join(', '),topHtml:topHtml?'<span id="'+editor.ui.spaceId('top')+'" class="cke_top cke_reset_all" role="presentation" style="height:auto">'+topHtml+'</span>':'',contentId:editor.ui.spaceId('contents'),bottomHtml:bottomHtml?'<span id="'+editor.ui.spaceId('bottom')+'" class="cke_bottom cke_reset_all" role="presentation">'+bottomHtml+'</span>':'',outerEl:CKEDITOR.env.ie?'span':'div'}));if(elementMode==CKEDITOR.ELEMENT_MODE_REPLACE){element.hide();container.insertAfter(element);}else
element.append(container);editor.container=container;topHtml&&editor.ui.space('top').unselectable();bottomHtml&&editor.ui.space('bottom').unselectable();var width=editor.config.width,height=editor.config.height;if(width)
container.setStyle('width',CKEDITOR.tools.cssLength(width));if(height)
editor.ui.space('contents').setStyle('height',CKEDITOR.tools.cssLength(height));container.disableContextMenu();CKEDITOR.env.webkit&&container.on('focus',function(){editor.focus();});editor.fireOnce('uiReady');}
CKEDITOR.domReady(function(){CKEDITOR.replaceClass&&CKEDITOR.replaceAll(CKEDITOR.replaceClass);});})();CKEDITOR.config.startupMode='wysiwyg';