
CKEDITOR.dom.domObject=function(nativeDomObject){if(nativeDomObject){this.$=nativeDomObject;}};CKEDITOR.dom.domObject.prototype=(function(){var getNativeListener=function(domObject,eventName){return function(domEvent){if(typeof CKEDITOR!='undefined')
domObject.fire(eventName,new CKEDITOR.dom.event(domEvent));};};return{getPrivate:function(){var priv;if(!(priv=this.getCustomData('_')))
this.setCustomData('_',(priv={}));return priv;},on:function(eventName){var nativeListeners=this.getCustomData('_cke_nativeListeners');if(!nativeListeners){nativeListeners={};this.setCustomData('_cke_nativeListeners',nativeListeners);}
if(!nativeListeners[eventName]){var listener=nativeListeners[eventName]=getNativeListener(this,eventName);if(this.$.addEventListener)
this.$.addEventListener(eventName,listener,!!CKEDITOR.event.useCapture);else if(this.$.attachEvent)
this.$.attachEvent('on'+eventName,listener);}
return CKEDITOR.event.prototype.on.apply(this,arguments);},removeListener:function(eventName){CKEDITOR.event.prototype.removeListener.apply(this,arguments);if(!this.hasListeners(eventName)){var nativeListeners=this.getCustomData('_cke_nativeListeners');var listener=nativeListeners&&nativeListeners[eventName];if(listener){if(this.$.removeEventListener)
this.$.removeEventListener(eventName,listener,false);else if(this.$.detachEvent)
this.$.detachEvent('on'+eventName,listener);delete nativeListeners[eventName];}}},removeAllListeners:function(){var nativeListeners=this.getCustomData('_cke_nativeListeners');for(var eventName in nativeListeners){var listener=nativeListeners[eventName];if(this.$.detachEvent)
this.$.detachEvent('on'+eventName,listener);else if(this.$.removeEventListener)
this.$.removeEventListener(eventName,listener,false);delete nativeListeners[eventName];}}};})();(function(domObjectProto){var customData={};CKEDITOR.on('reset',function(){customData={};});domObjectProto.equals=function(object){try{return(object&&object.$===this.$);}catch(er){return false;}};domObjectProto.setCustomData=function(key,value){var expandoNumber=this.getUniqueId(),dataSlot=customData[expandoNumber]||(customData[expandoNumber]={});dataSlot[key]=value;return this;};domObjectProto.getCustomData=function(key){var expandoNumber=this.$['data-cke-expando'],dataSlot=expandoNumber&&customData[expandoNumber];return(dataSlot&&key in dataSlot)?dataSlot[key]:null;};domObjectProto.removeCustomData=function(key){var expandoNumber=this.$['data-cke-expando'],dataSlot=expandoNumber&&customData[expandoNumber],retval,hadKey;if(dataSlot){retval=dataSlot[key];hadKey=key in dataSlot;delete dataSlot[key];}
return hadKey?retval:null;};domObjectProto.clearCustomData=function(){this.removeAllListeners();var expandoNumber=this.$['data-cke-expando'];expandoNumber&&delete customData[expandoNumber];};domObjectProto.getUniqueId=function(){return this.$['data-cke-expando']||(this.$['data-cke-expando']=CKEDITOR.tools.getNextNumber());};CKEDITOR.event.implementOn(domObjectProto);})(CKEDITOR.dom.domObject.prototype);