
CKEDITOR.editorConfig=function(config){config.plugins='dialogui,dialog,about,a11yhelp,dialogadvtab,basicstyles,bidi,blockquote,clipboard,button,panelbutton,panel,floatpanel,colorbutton,colordialog,templates,menu,contextmenu,div,resize,toolbar,elementspath,enterkey,entities,popup,filebrowser,find,fakeobjects,flash,floatingspace,listblock,richcombo,font,forms,format,horizontalrule,htmlwriter,iframe,wysiwygarea,image,indent,indentblock,indentlist,smiley,justify,menubutton,language,link,list,liststyle,magicline,maximize,newpage,pagebreak,pastetext,pastefromword,preview,print,removeformat,save,selectall,showblocks,showborders,bbcode,sourcearea,specialchar,scayt,stylescombo,tab,table,tabletools,undo,wsc,insertpre,videos,myoptions,confighelper';config.skin='moonocolor';config.removePlugins='dialogadvtab,div,filebrowser,flash,format,forms,iframe,liststyle,pagebreak,showborders,stylescombo,templates';config.disableObjectResizing=true;config.toolbar=[['Source','-','Save','NewPage'],['Cut','Copy','PasteText','PasteFromWord','-','Undo','Redo'],['Find','Replace','-','SelectAll','Scayt'],['Link','Unlink','Image','Smiley','SpecialChar','-','HorizontalRule'],['NumberedList','BulletedList','-','Outdent','Indent'],'/',['Bold','Italic','Underline','Strike','Superscript','Subscript','-','RemoveFormat'],['FontSize','Font','TextColor'],['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl'],['Blockquote','InsertCode','InsertPHP','-','Videos','Table'],['MyOptions','Maximize']];config.language='fa';config.image_previewText=' ';config.height='250';mycookie='';cname='myoptions_pastetext';var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i].trim();if(c.indexOf(name)==0)mycookie=c.substring(name.length,c.length);}
if(mycookie=='true')
{config.clipboard_defaultContentType='text';}
else
{config.clipboard_defaultContentType='html';}
mycookie='';cname='myoptions_clearautosave';var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i].trim();if(c.indexOf(name)==0)mycookie=c.substring(name.length,c.length);}
if(mycookie=='true')
{config.clearautosave=1;}
else
{config.clearautosave=0;}
config.placeholder='Type here...';};