
if(typeof CKEDITOR=='undefined')
CKEDITOR={};if(!CKEDITOR.loader){CKEDITOR.loader=(function(){var scripts={'_bootstrap':['config','creators/inline','creators/themedui','editable','ckeditor','plugins','scriptloader','style','tools','dom/comment','dom/elementpath','dom/text','dom/rangelist','skin'],'ckeditor':['ckeditor_basic','dom','dtd','dom/document','dom/element','dom/iterator','editor','event','htmldataprocessor','htmlparser','htmlparser/element','htmlparser/fragment','htmlparser/filter','htmlparser/basicwriter','template','tools'],'ckeditor_base':[],'ckeditor_basic':['editor_basic','env','event'],'command':[],'config':['ckeditor_base'],'dom':[],'dom/comment':['dom/node'],'dom/document':['dom/node','dom/window'],'dom/documentfragment':['dom/element'],'dom/element':['dom','dom/document','dom/domobject','dom/node','dom/nodelist','tools'],'dom/elementpath':['dom/element'],'dom/event':[],'dom/iterator':['dom/range'],'dom/node':['dom/domobject','tools'],'dom/nodelist':['dom/node'],'dom/domobject':['dom/event'],'dom/range':['dom/document','dom/documentfragment','dom/element','dom/walker'],'dom/rangelist':['dom/range'],'dom/text':['dom/node','dom/domobject'],'dom/walker':['dom/node'],'dom/window':['dom/domobject'],'dtd':['tools'],'editable':['editor','tools'],'editor':['command','config','editor_basic','filter','focusmanager','keystrokehandler','lang','plugins','tools','ui'],'editor_basic':['event'],'env':[],'event':[],'filter':['dtd','tools'],'focusmanager':[],'htmldataprocessor':['htmlparser','htmlparser/basicwriter','htmlparser/fragment','htmlparser/filter'],'htmlparser':[],'htmlparser/comment':['htmlparser','htmlparser/node'],'htmlparser/element':['htmlparser','htmlparser/fragment','htmlparser/node'],'htmlparser/fragment':['htmlparser','htmlparser/comment','htmlparser/text','htmlparser/cdata'],'htmlparser/text':['htmlparser','htmlparser/node'],'htmlparser/cdata':['htmlparser','htmlparser/node'],'htmlparser/filter':['htmlparser'],'htmlparser/basicwriter':['htmlparser'],'htmlparser/node':['htmlparser'],'keystrokehandler':['event'],'lang':[],'plugins':['resourcemanager'],'resourcemanager':['scriptloader','tools'],'scriptloader':['dom/element','env'],'selection':['dom/range','dom/walker'],'skin':[],'style':['selection'],'template':[],'tools':['env'],'ui':[],'creators/themedui':[],'creators/inline':[]};var basePath=(function(){if(CKEDITOR&&CKEDITOR.basePath)
return CKEDITOR.basePath;var path='';var scripts=document.getElementsByTagName('script');for(var i=0;i<scripts.length;i++){var match=scripts[i].src.match(/(^|.*?[\\\/])(?:_source\/)?core\/loader.js(?:\?.*)?$/i);if(match){path=match[1];break;}}
if(path.indexOf('://')==-1){if(path.indexOf('/')===0)
path=location.href.match(/^.*?:\/\/[^\/]*/)[0]+path;else
path=location.href.match(/^[^\?]*\//)[0]+path;}
return path;})();var timestamp=(CKEDITOR&&CKEDITOR.timestamp)||(new Date()).valueOf();var getUrl=function(resource){if(CKEDITOR&&CKEDITOR.getUrl)
return CKEDITOR.getUrl(resource);return basePath+resource+(resource.indexOf('?')>=0?'&':'?')+'t='+timestamp;};var pendingLoad=[];return{loadedScripts:[],scripts:scripts,loadPending:function(){var scriptName=pendingLoad.shift();if(!scriptName)
return;var scriptSrc=getUrl('core/'+scriptName+'.js');var script=document.createElement('script');script.type='text/javascript';script.src=scriptSrc;function onScriptLoaded(){CKEDITOR.loader.loadedScripts.push(scriptName);CKEDITOR.loader.loadPending();}
if(typeof(script.onreadystatechange)!=="undefined"){script.onreadystatechange=function(){if(script.readyState=='loaded'||script.readyState=='complete'){script.onreadystatechange=null;onScriptLoaded();}};}else{script.onload=function(){setTimeout(function(){onScriptLoaded(scriptName);},0);};}
document.body.appendChild(script);},load:function(scriptName,defer){if(('s:'+scriptName)in this.loadedScripts)
return;var dependencies=scripts[scriptName];if(!dependencies)
throw'The script name"'+scriptName+'" is not defined.';this.loadedScripts['s:'+scriptName]=true;for(var i=0;i<dependencies.length;i++)
this.load(dependencies[i],true);var scriptSrc=getUrl('core/'+scriptName+'.js');if(document.body&&(!document.readyState||document.readyState=='complete')){pendingLoad.push(scriptName);if(!defer)
this.loadPending();}else{this.loadedScripts.push(scriptName);document.write('<script src="'+scriptSrc+'" type="text/javascript"><\/script>');}}};})();}
if(CKEDITOR._autoLoad){CKEDITOR.loader.load(CKEDITOR._autoLoad);delete CKEDITOR._autoLoad;}